---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
#     - name: install apache on RHEL box
#       yum: name=httpd state=present
#       when: ansible_os_family == 'RedHat'
#     - name: install apahe on ubntu system
#       apt: name=apache2 state=present 
#       when: ansible_os_family == 'Ubuntu'
#     - name: start  httpd servic eon rhel7 box
#       service: name=httpd state=started enabled=yes
#     - service: name=apache2 state=started enabled=yes
      - include_tasks: rhel.yml
        when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
      - include_tasks: ubntu.yml
        when: ansible_distribution == 'Ubuntu'
     
