---
- hosts: all
  become: yes
  gather_facts: no
  vars: 
    xxx: $6$PcTDmzk6aOXu/EHa$L9bzShwDac6n5S2oXRABMIBIfvD1JLZtsg6swOB3wklv0RJ8/X6lVBKvFr4HSsMP1YSCa5NSpZw2M1lAzeCs6.
  tasks:
    - name: create group
      group: 
        name: ansiblegp
    - name: create users
      user: 
        name: "{{ item }}" 
        group: ansiblegp
        state: present 
        password: "{{ xxx }}" 
      with_items:
          - test1
          - test2
          - test3  
